### ISSUE TITLE
Segmentation Fault, killed or bus error with 2 sequence of 160kb

### ISSUE THREAD

**Issue by agroppi** [lorrainea/MARS#5]
I'm trying to run mars (latest version) on 2 chloroplasts DNA sequences (around 160kb each)
On a regular node of our cluster (256go RAM) I have 
- a segmentation fault with m1 option
- killed with m0 option

I tried to run mars on a bigmem node (1To RAM)
The amount of used RAM reach 400go and then I have a Bus error

**Comment by lorrainea** [comment]
Hi

Could you please share the sequence with me so I can understand a bit more what the code is doing.

Thank you

**Comment by agroppi** [comment]
Here is the input sequence file : 
[Marouch_cp_CGA_GetOrg.zip](https://github.com/lorrainea/MARS/files/2956953/Marouch_cp_CGA_GetOrg.zip)

Thanks

**Comment by lorrainea** [comment]
m1 option does not work well for long sequences. I will look into option m0 more within the next few weeks to try and improve the space used. For now, as your input only has 2 sequences please make use of this tool https://github.com/lorrainea/hCED which does exactly what MARS does just for a single pair of sequences.

**Comment by solonas13** [comment]
1/ Yes, this is exactly what MARS does.

2/ More or less yes, but MARS is generally more accurate. d0 and d1 is normal to give different results as the sequence comparison models are different.

3/ The reason why you run into trouble with MARS is because your sequences are relatively long and MARS is currently implemented to work in quadratic space. Lorraine is currently implementing MARS to work in linear space but this might take some time. In my opinion you should perform the following:

Let me denote by X1, X2, X3, and X4, your 4 sequences. Use hCED (which is an excellent tool for cyclic pairwise sequence comparison) to rotate X2, X3, and X4, with respect to X1. That is perform hCED(X1, X2), hCED(X1, X3) and then hCED(X1, X4). At this point, all sequences would have been rotated with respect to X1. Then run your favourite MSA algorithm with X1 and the rotated versions of X2, X3, and X4. Given that you only have 4 sequences and that these sequences are long this method should give you satisfactory results.

I hope this helps.

**Comment by agroppi** [comment]
Thanks for your detailed answer 👍 
I'll give it a try

**Comment by agroppi** [comment]
Dear @solonas13 
I perform the alignments as you suggested hCED(X1, X2), hCED(X1, X3) and then hCED(X1, X4)
But it seems that hCED is rotating both X1 and Xn and not only Xn against X1
Example : 
```
X1 (reference) : 
>X1
TGGGCGAACGACGGGAATTGAACCCGCGCATGGTGGATTCACAATCCACTGCCTTGATCCACTTGGCTACATCCGCCCCTTATACTATTACAAATATTTACAC...
```

hCED (X1,X2) result : 
```
>X1
AGGAGAAGAAGGAACCGAGAAGAAAGTATCAGCAACAACCGGTTTTATTACGGGACAGCTCATGATGTTCATATCGATCTATTATGTGCCTCTGCATCTAGC...
>X2
AGGAGAAGAAGGAACCGAGAAGAAAGTATCAGCAACAACCGGTTTTATTACGGGACAGCTCATGATGTTCATATCGATCTATTATGTGCCTCTGCATCTAGC...
```

hCED (X1,X3) result : 
```
>X1
GAAGAAGGAGAAGAAGGAACCGAGAAGAAAGTATCAGCAACAACCGGTTTTATTACGGGACAGCTCATGATGTTCATATCGATCTATTATGTGCCTCTGCA...
>X3
GAAGAAGGAGAAGAAGGAACCGAGAAGAAAGTATCAGCAACAACCGGTTTTATTACGGGACAGCTCATGATGTTCATATCGATCTATTATGTGCCTCTGCA...
```
My command line : 
```
   hCED \
  -i X1_X2.fasta \
  -o X1_X2_hCED_output.fasta \
  -R 0
```

**Comment by lorrainea** [comment]
Hi @agroppi 
This should not be the case at all and I have just run some experiments to check this. Please note that for a multifasta file with two input sequences, the first listed sequence should be the one to be rotated. So if your X1 is your reference you should list this as the second sequence in the input file so it does not get rotated. Let me know if this works.

**Comment by solonas13** [comment]
Ah OK. Then this makes sense. @agroppi your alignments seem to be good so please try to have X1 as the second sequence in the multiFASTA file.

**Comment by agroppi** [comment]
That's it!
Intuitively, I thought the first sequence was the reference.
I started again with X1 (reference) as the second sequence and it works.
Thank you @lorrainea @solonas13

**Comment by solonas13** [comment]
No problems. Thanks.
